# Generated by Django 4.0.3 on 2022-06-15 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_shedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='destination',
            field=models.CharField(default='galle', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buses',
            name='starting_point',
            field=models.CharField(default='mapalagama', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buses',
            name='sub_route_numer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turn_of_bus',
            name='last_location',
            field=models.CharField(default='wanduramba', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turn_of_bus',
            name='next_location',
            field=models.CharField(default='kimbikanda', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Active_buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.buses')),
            ],
        ),
    ]
