# Generated by Django 4.0.3 on 2022-06-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_buses_destination_buses_starting_point_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shedule',
            old_name='sheduled_times',
            new_name='destinaton_to_starting_point',
        ),
        migrations.AddField(
            model_name='shedule',
            name='starting_point_to_destination',
            field=models.CharField(default='12:30', max_length=1000),
            preserve_default=False,
        ),
    ]
