# Generated by Django 4.0.3 on 2022-06-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0008_shedule_times_of_turns'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn_of_bus',
            name='started',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turn_of_bus',
            name='starting_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
