# Generated by Django 4.0.3 on 2022-06-11 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_registration_number', models.CharField(max_length=32)),
                ('route_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turn_of_bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.TimeField()),
                ('current_longitude', models.FloatField()),
                ('current_altitude', models.FloatField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.buses')),
            ],
        ),
    ]
