# Generated by Django 4.0.3 on 2022-06-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0009_turn_of_bus_started_turn_of_bus_starting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_buses',
            name='starting_time',
            field=models.CharField(default='00:00', max_length=100),
            preserve_default=False,
        ),
    ]
