# Generated by Django 4.0.3 on 2022-06-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('route_number', models.IntegerField()),
                ('geographic_location', models.CharField(max_length=100)),
            ],
        ),
    ]
