# Generated by Django 4.0.3 on 2022-06-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_statics_searching'),
    ]

    operations = [
        migrations.AddField(
            model_name='statics_searching',
            name='endcoordinates',
            field=models.CharField(default='False', max_length=100),
        ),
        migrations.AddField(
            model_name='statics_searching',
            name='needdirections',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statics_searching',
            name='startcoordinates',
            field=models.CharField(default='False', max_length=100),
        ),
    ]
