# Generated by Django 4.0.3 on 2022-07-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_statics_searching_bus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='statics_searching',
            name='how_much_of_time',
            field=models.CharField(default='o mins', max_length=100),
        ),
    ]
