# Generated by Django 4.0.3 on 2022-06-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0006_alter_active_buses_bus_id_alter_shedule_bus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_buses',
            name='active_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
