# Generated by Django 4.0.3 on 2022-06-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_locations_starting_point_to_end_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='starting_point_to_end_point',
        ),
        migrations.AddField(
            model_name='locations',
            name='sub_route',
            field=models.IntegerField(default=0),
        ),
    ]
