# Generated by Django 4.0.3 on 2022-06-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_locations_route_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GettingLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingPoint', models.CharField(choices=[], max_length=200)),
                ('destinationPoint', models.CharField(choices=[], max_length=200)),
            ],
        ),
    ]
