# Generated by Django 4.0.3 on 2022-06-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_locations_starting_point_to_end_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.IntegerField()),
                ('sub_route', models.IntegerField(default=0)),
                ('list_of_locations', models.CharField(max_length=10000)),
            ],
        ),
    ]
