# Generated by Django 4.0.3 on 2022-06-29 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_statics_searching_endcoordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infromations_related_to_a_tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_api_time_estimation', models.CharField(max_length=100)),
                ('number_of_times_requested', models.IntegerField(default=0)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.statics_searching')),
            ],
        ),
    ]
