# Generated by Django 4.0.3 on 2022-06-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_infromations_related_to_a_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='statics_searching',
            name='bus_id',
            field=models.CharField(default='ND-1289', max_length=50),
            preserve_default=False,
        ),
    ]
