# Generated by Django 4.0.3 on 2022-08-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_statics_searching_how_much_of_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='statics_searching',
            name='times_of_shedules',
            field=models.CharField(default='', max_length=100),
        ),
    ]
